#!/bin/bash

find_utf()
{
  for file in "$@"
  do
    if [[ -d $file ]]; then  
      cd $file
      find_ascii $(ls)
      cd ..
    else
      if file -b $file | grep -c -q "UTF-8"; then 
        echo $file 
      fi
    fi
  done
}

find_utf "$@"


